export const MOBILETOPUP_PAGE = "MOBILETOPUP_PAGE";
export const SAGAS_MOBILETOPUP_PAGE = "SAGAS_MOBILETOPUP_PAGE";
export const MOBILETOPUP_OPERATORNAME = "MOBILETOPUP_OPERATORNAME";
export const MOBILETOPUP_CHILDPHONE = "MOBILETOPUP_CHILDPHONE";
