const messages: Record<string, string> = {
  "app.name": "allowance",
  "otp.mobileNumber": "شماره همراه",
  "otp.handleClick": "تایید و ادامه",
  "otp.verifyCode": "کد ارسال شده را وارد کنید",
  "otp.handleVerifyCode": "تایید کد",
  "otp.welcomeText": "به اپلیکشن ایکس خوش آمدید",
  "otp.nationalCode": "کد ملی",
  "entryType.description":
    "این اپلیکشن  برای شرکت راهگزین رایانه طراحی شده و هرگونه حق کپی از این اپلیکیشن محفوظ می باشد",
  "entryType.parentBotton": "ورود والدین",
  "entryType.childBotton": "ورود فرزندان",
  "login.title": "ورود",
  "login.userName": "نام کاربری",
  "login.password": "رمز عبور",
  "login.handleClick": "ورود",
  "login.fingerprint": "   ورود با اثر انگشت",
  "login.fingerproint-quesion": "   مایلید بعد از این با اثر انگشت وارد شوید؟",
  "login.FaceId": "ورود با تشخیص چهره",
  "signIn.noRegister": "قبلا ثبت نام نکرده‌اید؟",
  "signIn.forgetPassword": "رمز عبور خود را فراموش کرده اید؟",
  "home.transferMoney": "انتقال وجه",
  "home.addMoney": "افزایش حساب",
  "home.payable": "قابل پرداخت",
  "home.liable": "پس انداز",
  "home.rial": "ريال",
  "nationalCode.serialNumber":
    "شماره سریال پشت کارت ملی جدید و یا شماره پیگیری دریافت کارت ملی جدید را وارد نمایید.",
  "address.postalCode": "کدپستی",
  "address.telephone": "تلفن ثابت",
  "nationalCard.handleUpload": "آپلود و ادامه",
  "nationalCard.scan":
    "روی کارت ملی خود را مقابل دوربین قرار دهیدسپس دکمه اسکن را فشار دهید",
  "nationalCard.handleClick": "اسکن",
  cashDeposit: "افزایش حساب",
  amount: "مبلغ",
  cardNumber: "شماره کارت",
  cvv2: "cvv2",
  expirationDate: "تاریخ انقضا",
  getDynamicPass: "دریافت رمز پویا",
  secondPassword: "رمز دوم",
  pay: "پرداخت",
  transactionResid: "رسید تراکنش",
  sourcePan: "شماره کارت مبدا",
  transactionDate: "تاریخ و زمان",
  followUpCode: "شماره پیگیری",
  terminalNo: "شماره ترمینال",
  transferMoney: "انتقال وجه",
  addChild: "افزودن فرزند",
  "addChild.firstInput":
    " لطفا کدملی‌ و تاریخ تولد فرزند خود را جهت استعلام وارد نمائید.",
  "addCild.ageWarning": "محدوده سن فرزند باید بین ۹ تا ۱۵ سال باشد",
  "addChild.nickNameDescription":
    "در صورتی که فرزند خود را به نام دیگری صدا می زنید آن را وارد کنید.",
  "addCild.mobilePaymentTitle": "امکان پرداخت موبایلی برای فرزند",
  "addCild.mobilePaymentDescription":
    "در صورت انتخاب این گزینه شما میتوانید خرید‌های موبایلی را برای فرزندتان فعال کنید و برای هریک از آنها سقف تعیین نمائید.",
  "addCild.cardTitle": "می‌خواهم فرزندم کارت بانکی‌ داشته باشد.",
  "addCild.cardDescription":
    "در صورت انتخاب این گزینه و تائید شما در مرحله بعد، کارت صادر شده به آدرس شما ارسال میگردد.",
  inquiryErrorTitle: "هویتی با مشخصات وارد شده یافت نشد.",
  childAccount: "حساب کاربری فرزند",
  address: "آدرس",
  setting: "تنظیمات",
  "drawer.addChild": "افزودن فرزند",
  "drawer.setting": "تنظیمات اکانت ها",
  "drawer.bills": "صورتحساب",
  "drawer.help": "راهنمای برنامه",
  "drawer.suppurt": "پشتیبانی",
  "drawer.signOut": "خروج",
  addNewTask: "تعریف مسئولیت جدید",
  invoice: "صورتحساب",
  //tabbar
  home: "خانه",
  cards: "کارتها",
  saving: "پس انداز",
  pig: "پس انداز",
  more: "بیشتر",
  magic: "درآمد",
  destinationAccountOwner: "صاحب حساب مقصد",
  sourceAccountOwner: "صاحب حساب مبدا",
  traceNumber: "شماره پیگیری",
  terminalNumber: "شماره ترمینال",
  "earning.allowance": "پول توجیبی‌:",
  "earning.paymentDay": "روز پرداخت",
  "earning.taskTitle": "فعالیت‌های انجام شده در این هفته",
  "earning.taskDescription": "فعالیتی برای نمایش وجود ندارد.",
  "earning.otherPaymentsDescription": "پرداختی برای نمایش وجود ندارد.",
  "earning.other": "سایر",
  earning: "درآمد",
  "earning.justOnceActivity": "انجام فعالیت فقط یکبار",
  "earning.weeklyActivity": "انجام فعالیت به صورت هفتگی",
  "earning.addToPopularList": "افزودن به لیست پر مراجعه‌ها",
  "earning.confirmTask": "تائید فعالیت",
  "earning.paid": "واریز شده",
  "earning.unpaid": "واریز نشده",
  addNewTarget: "تعریف هدف پس انداز",
  transferMoneyToTarget: "انتقال وجه به هدف",
  spent: "مخارج",
  editTarget: "ویرایش هدف پس انداز",
  save: "ذخیره",
  finishTarget: "اتمام هدف",
  internetPackage: "بسته اینترنت",
  permanent: "دائمی",
  perpaid: "اعتباری",
  MCI: "همراه اول",
  IRANCELL: "ایرانسل",
  RIGHTEL: "رایتل",
  confirmPayment: "تائید پرداخت",
  continue: "ادامه",
  confirm: "تایید",
  qrHeader: "پرداخت با QR",
  edit: "ویرایش",
  mobileTopUp: "خرید شارژ موبایل",
  "mobileTopUp.phoneNum": "شماره موبایل",
  "mobileTopUp.description":
    "در صورت ترابرد، لطفا اپراتور جدید خود را انتخاب کنید.",
  "mobileTopUp.irancell": "ایرانسل",
  "mobileTopUp.hamrahaval": "همراه اول",
  "mobileTopUp.rightel": "رایتل",
  "mobileTopUp.paymentDescription":
    "سقف خرید شارژ برای شما ۱،۰۰۰،۰۰۰ ریال تعیین شده است.",
  verifyMobileTopUpPayment: "تایید پرداخت",
  qr_Payment: "پرداخت با QR",
  mobile_TopUp: "خرید شارژ",
  mobile_internet: "بسته اینترنت",
  mobile_bill: "قبض موبایل",
  mobileBillPayment: "پرداخت قبض موبایل",
  child_spending: "مخارج",
  "orderBabyCard.orderDescription":
    "کارتی وجود ندارد. لطفا جهت استفاده از امکانات برنامه برای او کارت سفارش دهید.",
  "orderBabyCard.activationDescription":
    "سفارش کارت با موفقیت ثبت شده است و طی‌ ۳ روز کاری به دست شما خواهد رسید. لطفا در صورت دریافت کارت با استفاده از گزینه فعالسازی، آن را فعال کنید.",
    "appUpdate.title": 'به روز رسانی برنامه',
    "appUpdate.dsc.codePush": 'برنامه مانی با موفقیت به‌روز‌رسانی شد. برای بهره‌مندی از قابلیت‌های جدید لیست شده در زیر، لطفا یک بار از برنامه خارج شوید و دوباره وارد شوید.',
    "appUpdate.dsc.light": 'با دریافت نسخه جدید (نام) از قابلیت‌های جدید این برنامه بهره مند شوید.'
};
export default messages;
